#!/usr/bin/env bash
# Monta /opt/vitrine/.env a partir de variáveis exportadas (CI injeta via SSH).
# PUBLIC_BASE_URL é o único ponto de verdade para URLs públicas.
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/vitrine}"
ENV_FILE="${APP_DIR}/.env"

: "${PUBLIC_BASE_URL:?PUBLIC_BASE_URL is required}"
: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${JWT_SECRET:?JWT_SECRET is required}"
: "${PASSWORD_PEPPER:?PASSWORD_PEPPER is required}"
: "${ENCRYPTION_KEY:?ENCRYPTION_KEY is required}"

# Remove trailing slash — URLs derivadas são montadas de forma consistente.
PUBLIC_BASE_URL="${PUBLIC_BASE_URL%/}"

export NODE_ENV="${NODE_ENV:-production}"
export TLS_ENABLED="${TLS_ENABLED:-false}"

# URLs públicas derivadas (path routing: /api, /admin).
export NEXT_PUBLIC_API_URL="${PUBLIC_BASE_URL}/api"
export NEXT_PUBLIC_SITE_URL="${PUBLIC_BASE_URL}"
export WEB_PUBLIC_URL="${PUBLIC_BASE_URL}"
export STORAGE_PUBLIC_BASE_URL="${PUBLIC_BASE_URL}/api/uploads"
export CORS_ORIGINS="${CORS_ORIGINS:-${PUBLIC_BASE_URL}}"
export API_INTERNAL_URL="${API_INTERNAL_URL:-http://api:3000}"

# Docker Swarm service hostnames (overlay network).
export POSTGRES_HOST="${POSTGRES_HOST:-postgres}"
export POSTGRES_PORT="${POSTGRES_PORT:-5432}"
export REDIS_HOST="${REDIS_HOST:-redis}"
export REDIS_PORT="${REDIS_PORT:-6379}"
export REDIS_CACHE_DB="${REDIS_CACHE_DB:-0}"
export REDIS_QUEUE_DB="${REDIS_QUEUE_DB:-1}"
export REDIS_TELEMETRY_DB="${REDIS_TELEMETRY_DB:-2}"

POSTGRES_USER_ENC="$(python3 -c "import urllib.parse; print(urllib.parse.quote('${POSTGRES_USER}', safe=''))")"
POSTGRES_PASSWORD_ENC="$(python3 -c "import urllib.parse; print(urllib.parse.quote('${POSTGRES_PASSWORD}', safe=''))")"
export DATABASE_URL="${DATABASE_URL:-postgresql://${POSTGRES_USER_ENC}:${POSTGRES_PASSWORD_ENC}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}"
export REDIS_URL="${REDIS_URL:-redis://${REDIS_HOST}:${REDIS_PORT}}"

export API_PORT="${API_PORT:-3000}"
export WEB_PORT="${WEB_PORT:-3001}"
export ADMIN_PORT="${ADMIN_PORT:-3002}"
export STORAGE_DRIVER="${STORAGE_DRIVER:-filesystem}"
export STORAGE_LOCAL_ROOT="${STORAGE_LOCAL_ROOT:-/app/uploads}"
export SEED_FORCE="${SEED_FORCE:-false}"
export TELEMETRY_BUFFER_ENABLED="${TELEMETRY_BUFFER_ENABLED:-true}"
export TELEMETRY_FLUSH_BATCH_SIZE="${TELEMETRY_FLUSH_BATCH_SIZE:-5000}"
export TELEMETRY_FLUSH_CRON="${TELEMETRY_FLUSH_CRON:-*/5 * * * *}"
export TELEMETRY_BUFFER_MAX_LEN="${TELEMETRY_BUFFER_MAX_LEN:-100000}"

mkdir -p "${APP_DIR}"

cat >"${ENV_FILE}" <<EOF
# Gerado por render-env.sh — não editar manualmente no VPS.
NODE_ENV=${NODE_ENV}
TLS_ENABLED=${TLS_ENABLED}
PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
WEB_PUBLIC_URL=${WEB_PUBLIC_URL}
API_INTERNAL_URL=${API_INTERNAL_URL}
STORAGE_PUBLIC_BASE_URL=${STORAGE_PUBLIC_BASE_URL}
CORS_ORIGINS=${CORS_ORIGINS}
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=${DATABASE_URL}
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_URL=${REDIS_URL}
REDIS_CACHE_DB=${REDIS_CACHE_DB}
REDIS_QUEUE_DB=${REDIS_QUEUE_DB}
REDIS_TELEMETRY_DB=${REDIS_TELEMETRY_DB}
API_PORT=${API_PORT}
WEB_PORT=${WEB_PORT}
ADMIN_PORT=${ADMIN_PORT}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-8h}
PASSWORD_PEPPER=${PASSWORD_PEPPER}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
REVALIDATE_SECRET=${REVALIDATE_SECRET:-}
SITE_NAME=${SITE_NAME:-Vitrine}
COMPANY_LEGAL_NAME=${COMPANY_LEGAL_NAME:-Vitrine Ltda}
CONTACT_EMAIL=${CONTACT_EMAIL:-contato@vitrine.com.br}
SITE_TAGLINE=${SITE_TAGLINE:-Curadoria inteligente}
AMAZON_AFFILIATE_TAG=${AMAZON_AFFILIATE_TAG:-}
SHOPEE_AFFILIATE_ID=${SHOPEE_AFFILIATE_ID:-}
EMAIL_FROM=${EMAIL_FROM:-noreply@example.com}
RESEND_API_KEY=${RESEND_API_KEY:-}
STORAGE_DRIVER=${STORAGE_DRIVER}
STORAGE_LOCAL_ROOT=${STORAGE_LOCAL_ROOT}
SEED_FORCE=${SEED_FORCE}
TELEMETRY_BUFFER_ENABLED=${TELEMETRY_BUFFER_ENABLED}
TELEMETRY_FLUSH_BATCH_SIZE=${TELEMETRY_FLUSH_BATCH_SIZE}
TELEMETRY_FLUSH_CRON=${TELEMETRY_FLUSH_CRON}
TELEMETRY_BUFFER_MAX_LEN=${TELEMETRY_BUFFER_MAX_LEN}
GA4_PROPERTY_ID=${GA4_PROPERTY_ID:-}
GA4_SERVICE_ACCOUNT_JSON=${GA4_SERVICE_ACCOUNT_JSON:-}
ACME_EMAIL=${ACME_EMAIL:-}
EOF

chmod 600 "${ENV_FILE}"
echo "Wrote ${ENV_FILE}"
